/* cache-bust */
// ── Amazon Now Egypt — facilities data ─────────────────
// Amazon Now = quick-commerce dark stores. Smaller, more numerous than FCs.

const BRANCHES = [
  { id: 1, code: "QCA1", name: "QCA1", zone: "General", type: "Station", openedAt: "2024-01-01", sqm: 400, manager: "N/A" },
  { id: 2, code: "QCA2", name: "QCA2", zone: "General", type: "Station", openedAt: "2024-01-01", sqm: 400, manager: "N/A" },
  { id: 3, code: "QCA5", name: "QCA5", zone: "General", type: "Station", openedAt: "2024-01-01", sqm: 400, manager: "N/A" },
  { id: 4, code: "QCA8", name: "QCA8", zone: "General", type: "Station", openedAt: "2024-01-01", sqm: 400, manager: "N/A" },
  { id: 5, code: "QCC8", name: "QCC8", zone: "General", type: "Station", openedAt: "2024-01-01", sqm: 400, manager: "N/A" },
];

const VENDORS = [
  { id: 1, name: "Sharkawy", specialty: "General", contact: "N/A", contractType: "Variable" },
  { id: 2, name: "DAR", specialty: "General", contact: "N/A", contractType: "Variable" },
  { id: 3, name: "Sherif Gamil", specialty: "General", contact: "N/A", contractType: "Variable" },
  { id: 4, name: "Individual", specialty: "General", contact: "N/A", contractType: "Variable" },
];

const AGENTS = [
  { id: 1, name: "M. Khalifa",      role: "Facilities Lead",     zone: "October & Zayed, Central Cairo" },
  { id: 2, name: "Karem Adel",      role: "Site Coordinator",    zone: "South Cairo" },
  { id: 3, name: "Ali Werdany",     role: "Site Coordinator",    zone: "East Cairo" },
  { id: 4, name: "Abdelrahman M.",  role: "Site Coordinator",    zone: "New Cairo" },
  { id: 5, name: "Mostafa Khaled",  role: "Regional Coordinator",zone: "Giza, Alex" },
];

const CATEGORIES = {
  "HVAC":              { icon: "ti-snowflake",    color: "#0E6BA8", types: ["AC unit", "Walk-in chiller", "Walk-in freezer", "Ice maker", "Air curtain", "Ventilation"] },
  "Civil":             { icon: "ti-tools",        color: "#7A6A50", types: ["Plumbing", "Painting", "Flooring", "Ceiling", "Wall / partition", "General civil"] },
  "Doors & Glass":     { icon: "ti-door",         color: "#0E6BA8", types: ["Glass door", "Roll-up door", "Door mechanism", "Window", "Storefront"] },
  "Electrical":        { icon: "ti-bolt",         color: "#B45309", types: ["Wiring", "Lighting", "UPS / battery", "Breaker / panel", "Generator"] },
  "Network & IT":      { icon: "ti-wifi",         color: "#1D4ED8", types: ["WiFi / network", "CCTV cameras", "Printer", "POS / scanner", "Cabling"] },
  "FF&E":              { icon: "ti-armchair-2",   color: "#6F37B0", types: ["Shelving", "Picking cart", "Workbench", "Office furniture"] },
  "Cleaning & Pest":   { icon: "ti-spray",        color: "#1F7A4D", types: ["Deep cleaning", "Pest control", "Waste removal"] },
  "Safety & Security": { icon: "ti-shield",       color: "#C92A2A", types: ["Fire system", "Alarm", "Access control", "Signage"] },
};

const STATUSES = [
  { key: "New",              cls: "badge-status-new",       desc: "Just reported, awaiting triage." },
  { key: "In Progress",      cls: "badge-status-progress",  desc: "Assigned, work underway." },
  { key: "Pending",          cls: "badge-status-pending",   desc: "Blocked — waiting for parts or info." },
  { key: "Waiting Approval", cls: "badge-status-waiting",   desc: "Cost over threshold — needs sign-off." },
  { key: "In Maintenance",   cls: "badge-status-maint",     desc: "Vendor on-site, repairing." },
  { key: "Closed",           cls: "badge-status-closed",    desc: "Resolved and signed off." },
  { key: "Rejected",         cls: "badge-status-rejected",  desc: "Not actionable / out of scope." },
  { key: "Duplicate",        cls: "badge-status-duplicate", desc: "Same as another open ticket." },
];

const PRIORITIES = [
  { key: "Low",       cls: "badge-prio-low"       },
  { key: "Medium",    cls: "badge-prio-medium"    },
  { key: "High",      cls: "badge-prio-high"      },
  { key: "Quotation", cls: "badge-prio-quotation" },
];

const MAINT_TYPES = ["Maintenance", "Modification", "Installation", "Supply", "Removal", "Inspection", "Emergency"];

// helpers used to build sample tickets
const d = (offsetDays) => {
  const x = new Date("2026-05-15");
  x.setDate(x.getDate() + offsetDays);
  return x.toISOString().split("T")[0];
};

const TICKETS = [
  { id: 1, code: "ANW-26-000", title: "Electricity", description: "صيانة برايز", branchId: 1, category: "Electrical", ticketType: "Electricity", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 400, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 2, code: "ANW-26-001", title: "Electricity", description: "إضافة برايز خارجي 12 علبة", branchId: 1, category: "Electrical", ticketType: "Electricity", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 3000, visitCost: 900, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 3, code: "ANW-26-002", title: "Electricity", description: "إضافة برايز خارجي10 علبة", branchId: 1, category: "Electrical", ticketType: "Electricity", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 2600, visitCost: 650, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 4, code: "ANW-26-003", title: "Electricity", description: "تركيب غطاء بواط لكل الفرع وايجار سلم", branchId: 1, category: "Electrical", ticketType: "Electricity", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 1840, visitCost: 200, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 5, code: "ANW-26-004", title: "Heaters", description: "تركيب وتشغيل السخان", branchId: 1, category: "HVAC", ticketType: "Heaters", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 300, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 6, code: "ANW-26-005", title: "IT", description: "توريد ووتر بروف راك", branchId: 1, category: "Network & IT", ticketType: "IT", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 800, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 7, code: "ANW-26-006", title: "Alumital Doors", description: "توريد وتركيب كالون ", branchId: 1, category: "Doors & Glass", ticketType: "Alumital Doors", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 685, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 8, code: "ANW-26-007", title: "Alumital Doors", description: "توريد وتركيب طقم مقبض وكالون", branchId: 1, category: "Doors & Glass", ticketType: "Alumital Doors", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 970, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 9, code: "ANW-26-008", title: "Construction", description: "تنفيذ باركينج", branchId: 1, category: "Civil", ticketType: "Construction", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 39885, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 10, code: "ANW-26-009", title: "Holes", description: "توريد وتركيب عتبة رخام", branchId: 1, category: "Civil", ticketType: "Holes", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 525, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 11, code: "ANW-26-010", title: "Holes", description: "ترميم ودهان", branchId: 1, category: "Civil", ticketType: "Holes", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 1000, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 12, code: "ANW-26-011", title: "Electricity", description: "صيانة برايز", branchId: 2, category: "Electrical", ticketType: "Electricity", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 700, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 13, code: "ANW-26-012", title: "Electricity", description: "إضافة برايز خارجي", branchId: 2, category: "Electrical", ticketType: "Electricity", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 1400, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 14, code: "ANW-26-013", title: "Electricity", description: "تركيب غطاء بواط لكل الفرع", branchId: 2, category: "Electrical", ticketType: "Electricity", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 1220, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 15, code: "ANW-26-014", title: "Electricity", description: "تجميع وصيانة الشفاط وتقفيل الشباك", branchId: 2, category: "Electrical", ticketType: "Electricity", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 150, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 16, code: "ANW-26-015", title: "Lighting", description: "إعادة تثبيت كشافات", branchId: 2, category: "Electrical", ticketType: "Lighting", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 100, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 17, code: "ANW-26-016", title: "Plumbing", description: "صيانة موتور الرفع", branchId: 2, category: "Civil", ticketType: "Plumbing", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 1025, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 18, code: "ANW-26-017", title: "Plumbing", description: "تغيير قلب خلاط ووصلة شجرة ومحبس وقنطرة", branchId: 2, category: "Civil", ticketType: "Plumbing", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 420, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 19, code: "ANW-26-018", title: "Plumbing", description: "إعادة تثبيت وتسليك الصرف", branchId: 2, category: "Civil", ticketType: "Plumbing", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 400, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 20, code: "ANW-26-019", title: "Alumital Doors", description: "توريد وتركيب مقابض وكالون", branchId: 2, category: "Doors & Glass", ticketType: "Alumital Doors", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 800, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 21, code: "ANW-26-020", title: "Holes", description: "ترميم ودهان", branchId: 2, category: "Civil", ticketType: "Holes", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 1000, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 22, code: "ANW-26-021", title: "Water dispenser", description: "تغيير جوان الحلة الداخلية", branchId: 2, category: "FF&E", ticketType: "Water dispenser", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 23, code: "ANW-26-022", title: "Electricity", description: "صيانة وتثبيت بنز الباب", branchId: 3, category: "Electrical", ticketType: "Electricity", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 24, code: "ANW-26-023", title: "Electricity", description: "صيانة برايز", branchId: 3, category: "Electrical", ticketType: "Electricity", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 430, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 25, code: "ANW-26-024", title: "Electricity", description: "إضافة برايز خارجي", branchId: 3, category: "Electrical", ticketType: "Electricity", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 2600, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 26, code: "ANW-26-025", title: "Electricity", description: "تركيب غطاء بواط لكل الفرع", branchId: 3, category: "Electrical", ticketType: "Electricity", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 1740, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 27, code: "ANW-26-026", title: "Lighting", description: "إعادة تثبيت كشافات", branchId: 3, category: "Electrical", ticketType: "Lighting", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 100, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 28, code: "ANW-26-027", title: "Electricity", description: "صيانة برايز", branchId: 4, category: "Electrical", ticketType: "Electricity", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 600, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 29, code: "ANW-26-028", title: "Electricity", description: "إضافة 14 علبة برايز خارجي", branchId: 4, category: "Electrical", ticketType: "Electricity", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 4550, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 30, code: "ANW-26-029", title: "Electricity", description: "تركيب غطاء بواط لكل الفرع", branchId: 4, category: "Electrical", ticketType: "Electricity", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 1600, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 31, code: "ANW-26-030", title: "UPS", description: "توريد وتركيب UPS", branchId: 4, category: "Electrical", ticketType: "UPS", agentId: 1, vendorId: 3, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 52000, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 32, code: "ANW-26-031", title: "Electricity", description: "إزالة الغطاء", branchId: 4, category: "Electrical", ticketType: "Electricity", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 33, code: "ANW-26-032", title: "Alumital Doors", description: "تركيب مقبض وعصفورة", branchId: 4, category: "Doors & Glass", ticketType: "Alumital Doors", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 600, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 34, code: "ANW-26-033", title: "Paint", description: "دهان الباب وإخفاء اللحامات", branchId: 4, category: "Civil", ticketType: "Paint", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 1200, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 35, code: "ANW-26-034", title: "Holes", description: "ترميم بفوم وتركيب زوي المونيوم", branchId: 4, category: "Civil", ticketType: "Holes", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 2050, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 36, code: "ANW-26-035", title: "Plumbing", description: "تغيير 2 شطاف داخلي و2 كوع", branchId: 4, category: "Civil", ticketType: "Plumbing", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 280, visitCost: 250, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 37, code: "ANW-26-036", title: "Plumbing", description: "تغيير السديلي والمانيجا", branchId: 4, category: "Civil", ticketType: "Plumbing", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 370, visitCost: 200, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 38, code: "ANW-26-037", title: "Plumbing", description: "تركيب جوان لكوع الصرف وجلب", branchId: 4, category: "Civil", ticketType: "Plumbing", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 485, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 39, code: "ANW-26-038", title: "Trolley", description: "تغيير العجل المكسور", branchId: 4, category: "FF&E", ticketType: "Trolley", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 350, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 40, code: "ANW-26-039", title: "Electricity", description: "إضافة برايز خارجي 10 علبة", branchId: 1, category: "Electrical", ticketType: "Electricity", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 2600, visitCost: 650, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 41, code: "ANW-26-040", title: "Lighting", description: "توريد وتركيب 6كشافات", branchId: 1, category: "Electrical", ticketType: "Lighting", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 3600, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 42, code: "ANW-26-041", title: "Air Curtains", description: "توريد وتركيب عدد 3 ستارة", branchId: 1, category: "HVAC", ticketType: "Air Curtains", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 11100, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 43, code: "ANW-26-042", title: "Ladder", description: "صيانة عدد 8 سلم شامل مسامير ولحام و3 فوم للستاير", branchId: 1, category: "FF&E", ticketType: "Ladder", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 1650, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 44, code: "ANW-26-043", title: "Cameras", description: "تعديل الفرع كله 49 كاميرا وإضافة 102 متر كات6", branchId: 1, category: "Network & IT", ticketType: "Cameras", agentId: 1, vendorId: 3, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 2500, visitCost: 10000, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 45, code: "ANW-26-044", title: "Installation - General", description: "تركيب صدادات لعجل الراك وقص الفاصل بالصاروخ", branchId: 1, category: "Civil", ticketType: "Installation - General", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 500, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 46, code: "ANW-26-045", title: "Cooling room", description: "صيانة باب الشيلر وباب الحمام", branchId: 1, category: "HVAC", ticketType: "Cooling room", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 650, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 47, code: "ANW-26-046", title: "Plastic curtains", description: "توريد وتركيب ستارة بلاستيك للدليفري", branchId: 1, category: "Doors & Glass", ticketType: "Plastic curtains", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 3900, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 48, code: "ANW-26-047", title: "Installation - General", description: "توريد عدد 2 صندوق اسعافات", branchId: 1, category: "Civil", ticketType: "Installation - General", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 1700, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 49, code: "ANW-26-048", title: "Lighting", description: "توريد وتركيب 3 كشاف طوارئ شامل النقل", branchId: 1, category: "Electrical", ticketType: "Lighting", agentId: 1, vendorId: 4, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 3150, visitCost: 700, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 50, code: "ANW-26-049", title: "Electricity", description: "تركيب شاشة وتوريد حامل وتثبيت استندات وتركيب البصمة", branchId: 2, category: "Electrical", ticketType: "Electricity", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 300, visitCost: 120, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 51, code: "ANW-26-050", title: "Air Curtains", description: "توريد وتركيب 3 ستارة شرائح", branchId: 2, category: "HVAC", ticketType: "Air Curtains", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 11700, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 52, code: "ANW-26-051", title: "Plumbing", description: "تغيير مسار الصرف وتزويد سخانات وتقفيل سليكون وتوصيل الصرف في المنور", branchId: 2, category: "Civil", ticketType: "Plumbing", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 6820, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 53, code: "ANW-26-052", title: "Ladder", description: "صيانة جميع السلالم", branchId: 2, category: "FF&E", ticketType: "Ladder", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 800, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 54, code: "ANW-26-053", title: "Installation - General", description: "نثبيت وتربيط جزئي للاستاندات", branchId: 2, category: "Civil", ticketType: "Installation - General", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 200, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 55, code: "ANW-26-054", title: "Installation - General", description: "توريد وتركيب 2 صندوق اسعافات", branchId: 2, category: "Civil", ticketType: "Installation - General", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 1700, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 56, code: "ANW-26-055", title: "Lighting", description: "توريد وتركيب 3 كشاف طوارئ شامل النقل توصيل الكهراء", branchId: 2, category: "Electrical", ticketType: "Lighting", agentId: 1, vendorId: 4, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 3150, visitCost: 700, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 57, code: "ANW-26-056", title: "Lighting", description: "توريد وتركيب 6كشافات", branchId: 3, category: "Electrical", ticketType: "Lighting", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 3900, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 58, code: "ANW-26-057", title: "Ladder", description: "صيانة جميع سلالم الفرع عدد 7", branchId: 3, category: "FF&E", ticketType: "Ladder", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 1150, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 59, code: "ANW-26-058", title: "Hand lift", description: "صيانة الهاند باليت في السبتية شامل اانقل", branchId: 3, category: "FF&E", ticketType: "Hand lift", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 4250, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 60, code: "ANW-26-059", title: "Installation - General", description: "توريد صندوق اسعافات", branchId: 3, category: "Civil", ticketType: "Installation - General", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 850, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 61, code: "ANW-26-060", title: "Plastic curtains", description: "توريد وتركيب 3 ستارة بلاستيك", branchId: 3, category: "Doors & Glass", ticketType: "Plastic curtains", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 11700, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 62, code: "ANW-26-061", title: "Installation - General", description: "تثبيت استاند الاستلام واعادة تربيطه وتأمينه", branchId: 3, category: "Civil", ticketType: "Installation - General", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 63, code: "ANW-26-062", title: "Cameras", description: "تم تعديل زوايا ١٢ كاميرا وتوريد ١٢ متر كات 6", branchId: 3, category: "Network & IT", ticketType: "Cameras", agentId: 1, vendorId: 3, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 500, visitCost: 2500, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 64, code: "ANW-26-063", title: "Installation - General", description: "إزالة غطاء الفاير", branchId: 3, category: "Civil", ticketType: "Installation - General", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 100, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 65, code: "ANW-26-064", title: "Alumital Doors", description: "توريد وتركيب طقم مقابض الوميتال وعصفورة حمام", branchId: 3, category: "Doors & Glass", ticketType: "Alumital Doors", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 850, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 66, code: "ANW-26-065", title: "Holes", description: "ترميم بمعجون وأسمنت وادبوند و5 عبوات فوم", branchId: 3, category: "Civil", ticketType: "Holes", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 1850, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 67, code: "ANW-26-066", title: "Water dispenser", description: "توريد دسبنسر جديد", branchId: 3, category: "FF&E", ticketType: "Water dispenser", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 4400, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 68, code: "ANW-26-067", title: "Lighting", description: "توريد وتركيب 3 كشاف طوارئ شامل النقل توصيل الكهراء", branchId: 3, category: "Electrical", ticketType: "Lighting", agentId: 1, vendorId: 4, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 3150, visitCost: 700, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 69, code: "ANW-26-068", title: "Lighting", description: "توريد وتركيب كشافات", branchId: 4, category: "Electrical", ticketType: "Lighting", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 1450, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 70, code: "ANW-26-069", title: "Electricity", description: "عمل 2 بريزة", branchId: 4, category: "Electrical", ticketType: "Electricity", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 450, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 71, code: "ANW-26-070", title: "Air Curtains", description: "توريد وتركيب 3 ستارة", branchId: 4, category: "HVAC", ticketType: "Air Curtains", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 11100, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 72, code: "ANW-26-071", title: "Holes", description: "إلغاء كتف جبس وترميم حائط وتغيير نص لوح جبس ومعجون ممتاز", branchId: 4, category: "Civil", ticketType: "Holes", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 900, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 73, code: "ANW-26-072", title: "Plumbing", description: "تعديل مسار خط تغذية الحمام الخارجي", branchId: 4, category: "Civil", ticketType: "Plumbing", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 3735, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 74, code: "ANW-26-073", title: "Plumbing", description: "تغيير السديلي", branchId: 4, category: "Civil", ticketType: "Plumbing", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 75, code: "ANW-26-074", title: "Plumbing", description: "تم صيانة السيفون", branchId: 4, category: "Civil", ticketType: "Plumbing", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 76, code: "ANW-26-075", title: "Plumbing", description: "تعديل وتوسيع مسار الصرف وضبط الميول وعزله حراري بجاسكت وارموفلكس لتقليل التجمد", branchId: 4, category: "Civil", ticketType: "Plumbing", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 4685, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 77, code: "ANW-26-076", title: "General", description: "توسيع شلف منطقة التسليم", branchId: 4, category: "Civil", ticketType: "General", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 250, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 78, code: "ANW-26-077", title: "Ladder", description: "صيانة جميع السلالم", branchId: 4, category: "FF&E", ticketType: "Ladder", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 940, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 79, code: "ANW-26-078", title: "Installation - General", description: "توريد وتركيب 2 صندوق اسعافات", branchId: 4, category: "Civil", ticketType: "Installation - General", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 1800, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 80, code: "ANW-26-079", title: "Plastic curtains", description: "توريد وتركيب ستارة بلاستيك للدليفري", branchId: 4, category: "Doors & Glass", ticketType: "Plastic curtains", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 3900, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 81, code: "ANW-26-080", title: "Lighting", description: "توريد وتركيب 3 كشاف طوارئ شامل النقل توصيل الكهراء", branchId: 4, category: "Electrical", ticketType: "Lighting", agentId: 1, vendorId: 4, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 3150, visitCost: 700, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 82, code: "ANW-26-081", title: "Electricity", description: "تزويد 9 علب و 15 برايز", branchId: 5, category: "Electrical", ticketType: "Electricity", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 2950, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 83, code: "ANW-26-082", title: "Electricity", description: "تركيب كشاف خارجي ضمان سنتين", branchId: 5, category: "Electrical", ticketType: "Electricity", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 2625, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 84, code: "ANW-26-083", title: "Electricity", description: "تقفيل لوحة الكهربا", branchId: 5, category: "Electrical", ticketType: "Electricity", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 60, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 85, code: "ANW-26-084", title: "General", description: "تركيب الصواعق والطفايات وصناديق الاسعاف", branchId: 5, category: "Civil", ticketType: "General", agentId: 1, vendorId: 3, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 1500, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 86, code: "ANW-26-085", title: "IT", description: "تركيب يونيفاي في التبريد ونقله مرة تانية وتعديل كاميرات", branchId: 5, category: "Network & IT", ticketType: "IT", agentId: 1, vendorId: 3, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 2500, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 87, code: "ANW-26-086", title: "Electricity", description: "تعديل خط كهربا الراوتر وربطه مع UPS", branchId: 5, category: "Electrical", ticketType: "Electricity", agentId: 1, vendorId: 3, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 1500, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 88, code: "ANW-26-087", title: "UPS", description: "توريد وتركيب UPS", branchId: 5, category: "Electrical", ticketType: "UPS", agentId: 1, vendorId: 3, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 52000, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 89, code: "ANW-26-088", title: "Holes", description: "ترميم جبس بورد", branchId: 5, category: "Civil", ticketType: "Holes", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 485, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 90, code: "ANW-26-089", title: "Electricity", description: "نقل الشاشة", branchId: 5, category: "Electrical", ticketType: "Electricity", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 120, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 91, code: "ANW-26-090", title: "Plumbing", description: "توصيل صرف تكييف", branchId: 5, category: "Civil", ticketType: "Plumbing", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 170, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 92, code: "ANW-26-091", title: "General", description: "توريد رامب حديد", branchId: 5, category: "Civil", ticketType: "General", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 8850, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 93, code: "ANW-26-092", title: "General", description: "صندوق اسعافات", branchId: 5, category: "Civil", ticketType: "General", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 900, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 94, code: "ANW-26-093", title: "Air Curtains", description: "توريد وتركيب 3 ستارة هوا شامل النقل", branchId: 5, category: "HVAC", ticketType: "Air Curtains", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 11100, visitCost: 1000, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 95, code: "ANW-26-094", title: "Plastic curtains", description: "توريد وتركيب ستارة بلاستيك شرايح للدليفري", branchId: 5, category: "Doors & Glass", ticketType: "Plastic curtains", agentId: 1, vendorId: 1, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 3900, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 96, code: "ANW-26-095", title: "Lighting", description: "توريد وتركيب 3 كشاف طوارئ شامل النقل توصيل الكهراء", branchId: 5, category: "Electrical", ticketType: "Lighting", agentId: 1, vendorId: 4, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 3150, visitCost: 700, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 97, code: "ANW-26-096", title: "AC", description: "صيانة عامة 10 تكييف داخلي وخارجي", branchId: 1, category: "HVAC", ticketType: "AC", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 3000, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 98, code: "ANW-26-097", title: "Cooling room", description: "صيانة عامة لوحدات التبريد خارجي", branchId: 1, category: "HVAC", ticketType: "Cooling room", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 400, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 99, code: "ANW-26-098", title: "Frozen room", description: "صيانة عامة لوحدات التجميد خارجي", branchId: 1, category: "HVAC", ticketType: "Frozen room", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 400, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 100, code: "ANW-26-099", title: "General", description: "تركيب حامل حديد لمراية الرامب", branchId: 3, category: "Civil", ticketType: "General", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 350, visitCost: 450, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 101, code: "ANW-26-100", title: "AC", description: "صيانة عامة 8 تكييف داخلي وخارجي وشحن فريون لجهاز واحد عطل EC", branchId: 3, category: "HVAC", ticketType: "AC", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 800, visitCost: 2400, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 102, code: "ANW-26-101", title: "Cooling room", description: "صيانة عامة لوحدات التبريد خارجي", branchId: 3, category: "HVAC", ticketType: "Cooling room", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 400, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 103, code: "ANW-26-102", title: "Frozen room", description: "صيانة عامة لوحدات التجميد خارجي", branchId: 3, category: "HVAC", ticketType: "Frozen room", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 400, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 104, code: "ANW-26-103", title: "Air Curtains", description: "صيانة عامة لعدد 4 ستاير الهواء", branchId: 3, category: "HVAC", ticketType: "Air Curtains", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 500, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 105, code: "ANW-26-104", title: "Water dispenser", description: "صيانة دسبنسر تغيير كباس وفلتر وشحن", branchId: 3, category: "FF&E", ticketType: "Water dispenser", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 3150, visitCost: 600, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 106, code: "ANW-26-105", title: "AC", description: "صيانة عامة 8 تكييف داخلي وخارجي", branchId: 2, category: "HVAC", ticketType: "AC", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 2400, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 107, code: "ANW-26-106", title: "Cooling room", description: "صيانة عامة لوحدات التبريد خارجي", branchId: 2, category: "HVAC", ticketType: "Cooling room", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 400, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 108, code: "ANW-26-107", title: "Frozen room", description: "صيانة عامة لوحدات التجميد خارجي", branchId: 2, category: "HVAC", ticketType: "Frozen room", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 400, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 109, code: "ANW-26-108", title: "Air Curtains", description: "صيانة عامة لستاير الهواء", branchId: 2, category: "HVAC", ticketType: "Air Curtains", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 375, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 110, code: "ANW-26-109", title: "Plumbing", description: "تغيير وصلة وقلب خلاط الحمام", branchId: 2, category: "Civil", ticketType: "Plumbing", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 360, visitCost: 150, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 111, code: "ANW-26-110", title: "Water dispenser", description: "صيانة دسبنسر تسريب من الحنفية والجوان", branchId: 2, category: "FF&E", ticketType: "Water dispenser", agentId: 1, vendorId: 2, status: "In Progress", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 112, code: "ANW-26-111", title: "AC", description: "صيانة عامة 10 تكييف وتركيب فانة", branchId: 4, category: "HVAC", ticketType: "AC", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 3000, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 113, code: "ANW-26-112", title: "Cooling room", description: "صيانة عامة لوحدات التبريد خارجي", branchId: 4, category: "HVAC", ticketType: "Cooling room", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 114, code: "ANW-26-113", title: "Frozen room", description: "صيانة عامة لوحدات التجميد خارجي", branchId: 4, category: "HVAC", ticketType: "Frozen room", agentId: 1, vendorId: 2, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 115, code: "ANW-26-114", title: "Holes", description: "شروخ وكسور في سيراميك الأرضيات", branchId: 1, category: "Civil", ticketType: "Holes", agentId: 1, vendorId: 2, status: "In Progress", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 0, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 116, code: "ANW-26-115", title: "Lighting", description: "توريد وتركيب 5 كشافات طولرئ إضافية", branchId: 3, category: "Electrical", ticketType: "Lighting", agentId: 1, vendorId: 4, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 5000, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" },
  { id: 117, code: "ANW-26-116", title: "Lighting", description: "توريد وتركيب 5 كشافات طولرئ إضافية", branchId: 2, category: "Electrical", ticketType: "Lighting", agentId: 1, vendorId: 4, status: "Closed", maintenanceType: "Maintenance", priority: "Medium", sparePartsCost: 5000, visitCost: 0, createdDate: "2026-03-01", closedDate: "2026-03-05", reporter: "System" }
];

// Make available on window for other scripts
export {
  BRANCHES, VENDORS, AGENTS, CATEGORIES, STATUSES, PRIORITIES, MAINT_TYPES, TICKETS,
};
